name: Deploy Frontend

on:
  push:
    branches: [ft/auth]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --configuration production

      - name: Setup SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          set -x
          mkdir -p ~/.ssh
          printf '%s\n' "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keygen -p \
            -P "$SSH_PASSPHRASE" \
            -N "" \
            -f ~/.ssh/deploy_key
          echo "ssh-keygen done"
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "keyscan done"

      - name: Deploy via rsync
        run: |
          rsync -az --delete \
            -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT }}" \
            dist/angular-tuto/browser/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/domains/saas.galyimmo.com/public_html/